### ISSUE TITLE
[13.0] Jobs stuck on status write

### ISSUE THREAD

**Issue by thomaspaulb** [novacode-nl/odoo-celery#43]
We're using the module for Odoo 13.0 and notice that sometimes jobs get stuck indefinitely on this line of code (PySpy shows the Odoo worker stuck here):

https://github.com/novacode-nl/odoo-celery/blob/13.0/celery/models/celery_task.py#L493

A mystery to me is that the "last query" shown for the associated Postgres process of the Odoo worker is a query (from `pg_stat_activity`) is one that was done somewhere in an Odoo module that we are using, it doesn't shown any kind of deadlocked query, it's just stuck. But because it holds locks on several records and the cursor was not closed, it holds up other Odoo processes as well, until finally exhausting all workers and hanging Odoo so that a restart is needed. 

Come to think of it, maybe I was looking at the wrong Postgres process, maybe I should have looked at another one - one that was trying to write the task status. I'll see if I can replicate it again.

In any case, it seems there is something wrong in the design of the module so that the update of the task status does not always finish.

1. Are you familiar with this bug?
2. Do you know of a fix?
3. Meanwhile we want to implement a workaround of setting a timeout and killing tasks that exceed that timeout, then retrying them; is that something you have already implemented or should we build it and make a PR.

**Comment by bobslee** [comment]
Hi,
No I'm not familiar with the issue you reported.
But I can imagine this issue could occur.

Maybe it's due to exceeding `limit_time` in combination with the `finally` in function `rpc_run_task`.
But I'm really not sure.

You could try to move (refactor) code from `finally` to the end of `try` and `except`.

Otherwise (to analyze, workaround) check out the Postgres `FOR UPDATE ...` locking clause.
However skipping or nowait of row-locks could leave records with inconsistent (wrong) data.
But at least you know those won't be stuck.
https://www.postgresql.org/docs/current/sql-select.html#SQL-FOR-UPDATE-SHARE

Example of it's usage in Odoo v13 (`stock.quant` update available).
https://github.com/odoo/odoo/blob/13.0/addons/stock/models/stock_quant.py#L426

Some other recommendation:
Use the OCA `queue_job` module. It's more mature and used (I expect).

Good luck!

**Comment by bobslee** [comment]
Just some quick pondering, you could try...

Perhaps calling a `flush()` or `flush_env()` after the first write could prevent the error.
It should write
https://github.com/novacode-nl/odoo-celery/blob/13.0/celery/models/celery_task.py#L432

So basically:

```python
with registry(self._cr.dbname).cursor() as result_cr:
    env = api.Environment(result_cr, self._uid, {})
    task.with_env(env).write(vals)
    task.flush()
```

Or...

```python
from .sql_db import flush_env

with registry(self._cr.dbname).cursor() as result_cr:
    env = api.Environment(result_cr, self._uid, {})
    task.with_env(env).write(vals)
    flush_env(result_cr)
```

**Comment by thomaspaulb** [comment]
I haven't had time to really dig into this anymore - what we've done as a workaround is to set `limit_time_real` to a lower value, so that tasks get killed if they are stuck too long. Since they don't occur too often and we don't have any other non-cron long-running tasks in this Odoo instance, it's a solution for the moment. In the longer run we're moving to OCA/queue, since it's better supported and makes for a simpler Odoo installation.

**Comment by thomaspaulb** [comment]
Thanks a lot though for responding!
